### PR TITLE
Update to 19.10, fix lapack patch, fix numpy deps

### PR DESCRIPTION
**Pull request by aldanor**
- Update dlib to v19.10
- Fix numpy deps as recommended [here](http://conda-forge.readthedocs.io/en/latest/meta.html#building-against-numpy)
- Fix out-of-date patch files

### CODE REVIEW

**Comment by aldanor** [comment]
@conda-forge-admin, please rerender

**Comment by aldanor** [comment]
Ok, the Linux builds are green, waiting on win/osx.

**Comment by aldanor** [comment]
Something's off with `target_compile_features` on OS X:

```
CMake Error at /Users/travis/miniconda3/conda-bld/dlib_1523209255322/work/dlib-19.10/dlib/cmake_utils/use_cpp_11.cmake:74 (target_compile_features):
  target_compile_features The compiler feature "cxx_thread_local" is not
  known to CXX compiler
  "Clang"
  version 6.1.0.6020053.
```

It must be this commit: https://github.com/davisking/dlib/commit/3b2d73db68d33b8d61f4b7906cfb52d90e353496#diff-d593bfc2d0dd0b78325fba99f82951fa

**Comment by aldanor** [comment]
@jschueller, @patricksnape - the build is green, could this get merged please?

Thanks!

**Comment by patricksnape** [comment]
Thanks @aldanor !

**Pull request merged**
