### PR TITLE
Add osx arm64

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by erykoff** [comment]
Fascinating.  I'm having trouble with the latest build of `cctools_osx-arm64=973.0.1-hd1d4517_6` and code signatures, and the simple case of c/c++ code works fine.  But where I was having problems was using python 3.8 and pybind11, just like the case here.  It may be a coincidence, and I haven't built a simple repro yet (https://github.com/conda-forge/cctools-and-ld64-feedstock/issues/50) but I wonder if pinning `cctools_osx-arm64=949.0.1` would work here. (I'd love to know if that worked, would be very interesting.)

**Comment by Tobias-Fischer** [comment]
Let's try @erykoff :)

Also invited you to the fork if you want to play around.

**Comment by erykoff** [comment]
My hunch maybe was wrong, but perhaps the osx-64 version should match?

**Comment by Tobias-Fischer** [comment]
Still not. Any other ideas?

**Comment by Tobias-Fischer** [comment]
Hi @aldanor @patricksnape - it would be great if you could have a look at this PR. Thanks!

**Comment by Tobias-Fischer** [comment]
@conda-forge/core - sorry to ping you, but I haven't heard from the maintainers. Could you please merge this in?

Thanks!

**Comment by wolfv** [comment]
Would you mind adding yourself to the maintainers list?

**Comment by Tobias-Fischer** [comment]
Done @wolfv

**Comment by wolfv** [comment]
I put this on automerge!

**Pull request merged**
